### ISSUE TITLE
Radio Channel

### ISSUE THREAD

**Issue by zek0** [alcapone-dev/ls-radio#1]
Im not shure about issue thi or not, but it is possible open "Radio channel" instead "Call channel"?

**Comment by alcapone-dev** [comment]
Hello!

Radio channels (ie those with the so-called click) are in TokoVOIP from 1-100. Channels over 100 are channels that do not have radio sound and radio click sound. However, when it comes to the names of channels that are displayed, we can set them in the file: https://github.com/Itokoyamato/TokoVOIP_TS3/blob/master/fivem_script/tokovoip_script/s_config.lua

**Comment by zek0** [comment]
Thank you!
